# Generated by Django 2.1.5 on 2019-01-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_auto_20190112_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='done',
            field=models.BooleanField(default=True),
        ),
    ]
