# Generated by Django 2.1.5 on 2019-01-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_post_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
